load:
  type: constant
  stages:
  - rate: 1
    duration: 30
vllm:
  api: completion
  model_name: meta-llama/Llama-2-7b-hf
  url: http://llama3-8b-vllm-service:8000
tokenizer:
  pretrained_model_name_or_path: meta-llama/Llama-2-7b-hf
  token: my-token
data:
  type: shareGPT
