data:
  type: mock
load:
  type: constant
  rate: 1
  duration: 2
report:
  name: openai-community-gpt2-test
metrics:
  url: http://0.0.0.0:8000/metrics
vllm:
  model_name: openai-community/gpt2
  url: http://0.0.0.0:8000