apiVersion: batch/v1
kind: Job
metadata:
  name: inference-perf
  labels:
    app: inference-perf
spec:
  template:
    metadata:
      labels:
        app: inference-perf
    spec:
      containers:
        - name: inference-perf
          image: <your image here>
          imagePullPolicy: Always
          command: ["inference-perf"]
          args: ["--config_file", "/etc/config/config.yml"]
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
              readOnly: true
      restartPolicy: Never
      volumes:
        - name: config-volume
          configMap:
            name: inference-perf-config