# Copyright 2025 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
OTel Trace Replay Data Generator

This module provides a data generator that replays LLM requests from OpenTelemetry trace files.
It processes OTel JSON traces, extracts LLM calls, infers dependencies, and replays them
with proper timing and dependency enforcement.

Output-aware replay
-------------------
When a call has "output" segments (i.e., a predecessor's output was injected as an assistant
message in the original trace), the replayer substitutes the recorded assistant message content
with the *actual* output generated by the predecessor call at replay time.

This ensures that growing-context patterns (multi-turn conversations, agent chains) are replayed
faithfully: the KV cache sees the real generated text, not the static recorded text.

The substitution is performed in `load_lazy_data` using the `NodeOutputRegistry`, which maps
node_id → actual output text. All registry data is stored in per-worker plain dicts; session-to-
worker affinity ensures that the node writing an output and the nodes reading it always run on
the same worker process.

The actual output is captured in `OTelChatCompletionAPIData.process_response`, which overrides
the base `ChatCompletionAPIData.process_response` to register the output after each LLM call.

Cross-process state
-------------------
Two orthogonal coordination problems exist in this system:

  Problem A — intra-worker, between coroutines on the same event loop:
    A node waits for its predecessor's output before building its request.
    Handled by NodeOutputRegistry using plain dicts and asyncio.Event.
    No IPC involved; session-to-worker affinity makes cross-process sharing unnecessary.

  Problem B — cross-process, worker → main process:
    The main process drives the session pool loop and needs to know when sessions
    complete and whether they failed. Workers produce these facts.
    Handled by SessionSharedState using Manager.dict() for both signals.

OTelChatCompletionAPIData holds refs to both objects and uses each for its
appropriate purpose. SessionSharedState is the single place where Manager.dict()
instances are created and owned.
"""

import asyncio
import glob
import json
import logging
import random
import time
from dataclasses import dataclass, field, replace as dc_replace
from multiprocessing.managers import SyncManager
from pathlib import Path
from typing import Any, Dict, List, Optional, Set

from aiohttp import ClientResponse

from inference_perf.apis import (
    ChatCompletionAPIData,
    InferenceAPIData,
    InferenceInfo,
    LazyLoadInferenceAPIData,
    SessionLifecycleMetric,
)
from inference_perf.apis.chat import ChatMessage
from inference_perf.config import APIConfig, APIType, DataConfig
from inference_perf.datagen.base import SessionGenerator, LazyLoadDataMixin
from inference_perf.datagen.otel_trace_to_replay_graph import (
    InputSegment,
    ReplayGraph,
    build_raw_calls,
    build_graph,
)
from inference_perf.utils.custom_tokenizer import CustomTokenizer

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# SessionGraphState — tracks graph traversal state for one session
# ---------------------------------------------------------------------------


@dataclass
class SessionGraphState:
    """Tracks graph traversal state for one session.

    Manages which nodes are ready to dispatch, which have been dispatched,
    and which have completed. Used for graph-based traversal.
    """

    session_id: str
    graph: ReplayGraph
    ready_nodes: Set[str]  # node_ids ready to dispatch (predecessors done)
    dispatched_nodes: Set[str]  # node_ids already dispatched
    completed_nodes: Set[str]  # node_ids that have completed
    node_completion_times: Dict[str, float]  # node_id → completion timestamp
    is_active: bool = False  # Is this session currently active?
    is_complete: bool = False  # Has this session finished all nodes?


# ---------------------------------------------------------------------------
# OTelInferenceInfo — InferenceInfo subclass that carries the output text
# ---------------------------------------------------------------------------


class OTelInferenceInfo(InferenceInfo):
    """InferenceInfo subclass that also carries the raw output text.

    Inherits all fields from InferenceInfo (input_tokens, output_tokens, etc.)
    and adds output_text so the OTel replay path can register the actual
    generated text in the NodeOutputRegistry without touching the base class.
    """

    output_text: Optional[str] = None


# ---------------------------------------------------------------------------
# SessionSharedState — all cross-process state in one place
# ---------------------------------------------------------------------------


class SessionSharedState:
    """Owns all state that must cross the worker → main-process boundary.

    Two facts need to be visible to the main process while workers are running:
      1. Which nodes have completed (so the main process can detect session completion).
      2. Which sessions have failed (so workers can skip dependent nodes and the
         main process can retire failed sessions).

    Both are stored in Manager.dict() instances so writes on any worker are
    immediately visible to every other process. This is the *only* place in the
    OTel replay path where Manager proxies are created.

    Usage:
        shared = SessionSharedState(mp_manager)   # main process, before fork
        # workers call shared.record_node_completed() and shared.mark_session_failed()
        # main process calls shared.is_node_completed() and shared.is_session_failed()
    """

    def __init__(self, manager: Optional[SyncManager] = None) -> None:
        if manager is not None:
            self._node_completions: Dict[str, float] = manager.dict()  # type: ignore[assignment]
            self._failed_sessions: Dict[str, bool] = manager.dict()  # type: ignore[assignment]
        else:
            self._node_completions = {}
            self._failed_sessions = {}

    # -- node completion --

    def record_node_completed(self, qualified_node_id: str, completion_time: float) -> None:
        """Record that a node has completed. Called from worker processes."""
        self._node_completions[qualified_node_id] = completion_time
        logger.debug(f"Recorded completion for node {qualified_node_id}")

    def is_node_completed(self, qualified_node_id: str) -> bool:
        """Return True if the node has been recorded as completed."""
        return qualified_node_id in self._node_completions

    def get_node_completion_time(self, qualified_node_id: str) -> Optional[float]:
        """Return completion timestamp for a node, or None if not yet completed."""
        return self._node_completions.get(qualified_node_id)

    # -- session failure --

    def mark_session_failed(self, session_id: str) -> None:
        """Mark a session as failed. Called from worker processes."""
        self._failed_sessions[session_id] = True
        logger.debug(f"Marked session {session_id} as failed")

    def is_session_failed(self, session_id: str) -> bool:
        """Return True if the session has been marked as failed."""
        return self._failed_sessions.get(session_id, False)


# ---------------------------------------------------------------------------
# NodeOutputRegistry — intra-worker output and message store
# ---------------------------------------------------------------------------


class NodeOutputRegistry:
    """Per-worker registry mapping node_id → actual output text and input messages.

    All data is stored in plain in-process dicts. Session-to-worker affinity
    guarantees that the node writing an output and the nodes reading it always
    run on the same worker process, so no IPC is needed here.

    Async waiting between coroutines on the same event loop is handled via
    asyncio.Event — one per node, allocated on first demand.

    This class has no Manager dependency. All cross-process state lives in
    SessionSharedState.

    Usage:
        registry = NodeOutputRegistry()
        # workers call registry.record(node_id, text, messages) after each LLM call
        # dependent nodes call await registry.require_async(node_id) before dispatching
    """

    def __init__(self) -> None:
        # Output text and input messages: plain dicts, same-worker only.
        self._node_output_text: Dict[str, str] = {}
        self._node_input_messages: Dict[str, Any] = {}

        # One asyncio.Event per node. Only accessed from coroutines on this
        # worker's single event loop; no lock needed.
        self._node_events: Dict[str, asyncio.Event] = {}

    def record(self, node_id: str, output_text: str, messages: List[Any]) -> None:
        """Register output for a completed node and wake any async waiters."""
        self._node_output_text[node_id] = output_text
        if messages:
            self._node_input_messages[node_id] = list(messages)

        # Signal any coroutine waiting on this node (same worker only).
        if node_id in self._node_events:
            self._node_events[node_id].set()
            logger.debug(f"Set asyncio.Event for node {node_id}")

    def get(self, node_id: str) -> Optional[str]:
        """Return the output text for node_id, or None if not yet registered."""
        return self._node_output_text.get(node_id)

    def get_output_by_node_id(self, node_id: str) -> Optional[str]:
        """Return the output text for a given node_id."""
        return self._node_output_text.get(node_id)

    def get_messages_by_node_id(self, node_id: str) -> Optional[List[Any]]:
        """Return the input messages for a given node_id.

        Args:
            node_id: The node ID to look up

        Returns:
            List of input messages, or None if not found
        """
        return self._node_input_messages.get(node_id)

    def get_node_ids(self) -> List[str]:
        """Return all registered node IDs.

        Returns:
            List of all node IDs that have registered outputs
        """
        return list(self._node_output_text.keys())

    async def require_async(self, node_id: str, timeout_sec: float = 3600.0) -> str:
        """Wait asynchronously for a node's output.

        If the output is already available, returns immediately. Otherwise suspends
        the calling coroutine until record() is called for this node_id, then resumes.

        Raises:
            TimeoutError: if output not available within timeout_sec
        """
        # Fast path: predecessor already completed.
        output = self._node_output_text.get(node_id)
        if output is not None:
            return output

        # Create the event before any await point. Because asyncio is cooperative,
        # record() cannot run between this line and the event.wait() below, so there
        # is no window where the event could be set before we start waiting.
        if node_id not in self._node_events:
            self._node_events[node_id] = asyncio.Event()
        event = self._node_events[node_id]

        # Second fast-path check: no await has occurred since the first check,
        # but be defensive in case this method's call site changes in the future.
        output = self._node_output_text.get(node_id)
        if output is not None:
            return output

        logger.debug(f"Node {node_id} waiting on asyncio.Event (zero threads)")

        try:
            await asyncio.wait_for(event.wait(), timeout=timeout_sec)
        except asyncio.TimeoutError:
            raise TimeoutError(
                f"NodeOutputRegistry: output for '{node_id}' not available after "
                f"{timeout_sec:.1f}s. Check that the predecessor is not blocked or failed."
            )

        # record() writes _node_output_text before calling event.set(). Both run on
        # the same single-threaded event loop, so the value is guaranteed to be present here.
        output = self._node_output_text.get(node_id)
        assert output is not None, (
            f"asyncio.Event fired for {node_id} but output missing from local cache — "
            "this is a bug in record()"
        )
        logger.debug(f"Node {node_id} woke from asyncio.Event")
        return output


# ---------------------------------------------------------------------------
# OTelChatCompletionAPIData — captures output and registers it in the registry
# ---------------------------------------------------------------------------


class OTelChatCompletionAPIData(ChatCompletionAPIData):
    """ChatCompletionAPIData subclass for OTel trace replay.

    Overrides process_response to:
    1. Extract the actual output text from the LLM response.
    2. Register it in the NodeOutputRegistry under this call's node_id.
    3. Return OTelInferenceInfo (InferenceInfo subclass) with output_text populated.

    The registry and node_id are passed at construction time via Pydantic fields.
    arbitrary_types_allowed is required because NodeOutputRegistry and
    SessionSharedState are not Pydantic models.

    Dependency handling:
    - predecessor_node_ids: List of nodes that must complete before this one
    - wait_ms: Additional delay after predecessors complete
    - input_segments: Segment decomposition for output substitution
    - original_messages: Original messages before substitution (used as template)
    """

    model_config = {"arbitrary_types_allowed": True}

    node_id: str
    registry: NodeOutputRegistry
    shared_state: SessionSharedState

    # Dependency information for async waiting
    predecessor_node_ids: List[str] = field(default_factory=list)
    wait_ms: int = 0
    input_segments: List[InputSegment] = field(default_factory=list)
    original_messages: List[Dict[str, Any]] = field(default_factory=list)
    expected_output_content: Optional[str] = None

    # Flag to skip HTTP request (set when session fails)
    skip_request: bool = False

    async def wait_for_predecessors_and_substitute(self) -> None:
        """Wait for all predecessor nodes to complete, then substitute output segments.

        Called by the worker before dispatching the HTTP request. Each predecessor
        is awaited via asyncio.Event, so the coroutine suspends without consuming
        any OS threads. All predecessors are waited in parallel via asyncio.gather.

        Requires all nodes of this session to run on the same worker, which is
        enforced by session-to-worker affinity in get_session_events().
        """
        # Extract session_id from node_id (format: "session_id:node_xxx")
        session_id = self.node_id.split(":")[0] if ":" in self.node_id else self.node_id

        # Pre-wait check: if session already failed, skip immediately.
        if self.shared_state.is_session_failed(session_id):
            logger.info(f"Node {self.node_id} skipping - session {session_id} has failed (pre-wait check)")
            self.skip_request = True
            self.registry.record(self.node_id, "", self.messages)
            self.shared_state.record_node_completed(self.node_id, time.perf_counter())
            return

        if self.predecessor_node_ids:
            logger.debug(
                f"Node {self.node_id} waiting for {len(self.predecessor_node_ids)} "
                f"predecessor(s)"
            )
            # Wait for all predecessors in parallel before proceeding.
            await asyncio.gather(*[
                self.registry.require_async(node_id, timeout_sec=3600.0)
                for node_id in self.predecessor_node_ids
            ])
            logger.debug(f"Node {self.node_id} all predecessors done")

            # Post-wait check: a predecessor may have failed while we were waiting.
            if self.shared_state.is_session_failed(session_id):
                logger.info(f"Node {self.node_id} skipping - session {session_id} has failed (post-wait check)")
                self.skip_request = True
                self.registry.record(self.node_id, "", self.messages)
                self.shared_state.record_node_completed(self.node_id, time.perf_counter())
                return

        # Wait additional delay specified in wait_ms
        if self.wait_ms > 0:
            wait_sec = self.wait_ms / 1000.0
            logger.debug(f"Node {self.node_id} waiting {wait_sec:.3f}s (wait_ms={self.wait_ms})")
            await asyncio.sleep(wait_sec)

        # Substitute output segments with actual predecessor outputs.
        if any(seg.type == "output" or seg.type == "shared" for seg in self.input_segments):
            logger.debug(f"Node {self.node_id} substituting output/shared segments")
            substituted = self._build_messages_with_substitution()
            self.messages = [
                ChatMessage(role=m["role"], content=m["content"])
                for m in substituted
            ]
            logger.debug(f"Node {self.node_id} substitution complete, {len(self.messages)} messages")

    def _build_messages_with_substitution(self) -> List[Dict[str, Any]]:
        """Build messages with output segments substituted with actual predecessor outputs.

        For assistant messages, we substitute their output messages with the actual output.
        """
        if not self.input_segments:
            return self.original_messages

        result = []
        cursor = 0

        for seg in self.input_segments:
            seg_msgs = self.original_messages[cursor : cursor + seg.message_count]

            if seg.type == "output":
                # Output segment: substitute with actual output from the specific predecessor
                if seg.source_node_id:
                    actual_output = self.registry.get_output_by_node_id(seg.source_node_id)
                    logger.debug(
                        f"Registry get for node {self.node_id} output segment from {seg.source_node_id} generated: {actual_output}"
                    )

                    if actual_output:
                        for msg in seg_msgs:
                            substituted = dict(msg)
                            substituted["content"] = actual_output
                            result.append(substituted)
                        logger.debug(
                            f"Node {self.node_id}: substituted output segment with actual output from {seg.source_node_id}"
                        )
                    else:
                        logger.warning(
                            f"Node {self.node_id}: output segment from {seg.source_node_id} "
                            f"not available, using recorded content"
                        )
                        result.extend(seg_msgs)
                else:
                    logger.warning(f"Node {self.node_id}: output segment has no source_node_id, using recorded content")
                    result.extend(seg_msgs)
            elif seg.type == "shared":
                seg_msgs_from_parent = self.registry.get_messages_by_node_id(seg.source_node_id)
                if seg_msgs_from_parent is None:
                    logger.error(
                        f"CRITICAL: Node {self.node_id} shared segment from {seg.source_node_id} "
                        f"has no messages in registry (should not happen after require_async)"
                    )
                    # Fallback to original messages
                    result.extend(seg_msgs)
                else:
                    logger.debug(
                        f"Registry get for node {self.node_id} from {seg.source_node_id} "
                        f"shared segment num messages in parent node: {len(seg_msgs_from_parent)}"
                    )
                    if len(seg_msgs_from_parent) != len(seg_msgs):
                        logger.error(
                            f"Node {self.node_id} shared segment from {seg.source_node_id} "
                            f"had different number of messages in parent node: {len(seg_msgs_from_parent)}, "
                            f"num messages in seg: {len(seg_msgs)}"
                        )
                    for msg in seg_msgs_from_parent:
                        result.append(dict(msg))
            elif seg.type == "unique":
                # Unique message, keep as-is
                for msg in seg_msgs:
                    result.append(msg)
            else:
                # Unknown segment type, keep as-is
                result.extend(seg_msgs)

            cursor += seg.message_count

        return result

    def on_completion(self, info: InferenceInfo) -> None:
        """Called after every request completes (real or mock) to register output and unblock successors."""
        output_text = info.output_text if isinstance(info, OTelInferenceInfo) else ""
        output_text = output_text or ""
        self.registry.record(self.node_id, output_text, self.messages)
        logger.debug(
            f"calling registry record for node {self.node_id} num input messages {len(self.messages)} and output: {output_text}"
        )
        self.shared_state.record_node_completed(self.node_id, time.perf_counter())
        logger.debug(f"Recorded node completion in shared state for {self.node_id}")

    async def process_response(
        self,
        response: ClientResponse,
        config: APIConfig,
        tokenizer: CustomTokenizer,
        lora_adapter: Optional[str] = None,
    ) -> OTelInferenceInfo:
        """Process the LLM response, capture output text, and register it."""
        logger.debug(f"process_response called for node {self.node_id}")
        output_text: str = ""

        if config.streaming:
            output_text = ""
            output_token_times: List[float] = []
            buffer = b""
            async for chunk in response.content.iter_any():
                buffer += chunk
                while b"\n\n" in buffer:
                    message, buffer = buffer.split(b"\n\n", 1)
                    output_token_times.append(time.perf_counter())
                    for line in message.split(sep=b"\n"):
                        if line.startswith(b"data:"):
                            data_str = line.removeprefix(b"data: ").strip()
                            if data_str == b"[DONE]":
                                break
                            try:
                                data = json.loads(data_str)
                                choices = data.get("choices", [])
                                if choices:
                                    delta = choices[0].get("delta", {})
                                    content = delta.get("content")
                                    if content:
                                        output_text += content
                            except (json.JSONDecodeError, IndexError):
                                continue
                    else:
                        continue
                    break

            prompt_text = "".join([msg.content for msg in self.messages if msg.content])
            prompt_len = tokenizer.count_tokens(prompt_text)
            output_len = tokenizer.count_tokens(output_text)
            info = OTelInferenceInfo(
                input_tokens=prompt_len,
                output_tokens=output_len,
                output_token_times=output_token_times,
                lora_adapter=lora_adapter,
                output_text=output_text or None,
            )
        else:
            data = await response.json()
            prompt_len = tokenizer.count_tokens("".join([m.content for m in self.messages]))
            choices = data.get("choices", [])
            if choices:
                output_text = "".join([choice.get("message", {}).get("content", "") for choice in choices])
            output_len = tokenizer.count_tokens(output_text)
            info = OTelInferenceInfo(
                input_tokens=prompt_len,
                output_tokens=output_len,
                lora_adapter=lora_adapter,
                output_text=output_text or None,
            )

        # Register output and notify successors.
        self.on_completion(info)

        if output_text:
            logger.debug(f"Registered output for node {self.node_id}: {len(output_text)} chars : {output_text}")
        else:
            logger.debug(f"Registered empty output for node {self.node_id}")

        return info

    async def process_failure(
        self,
        response: Optional[ClientResponse],
        config: APIConfig,
        tokenizer: CustomTokenizer,
        exception: Exception,
        lora_adapter: Optional[str] = None,
    ) -> InferenceInfo:
        """Process a failed request and signal failure to main process.

        This method is called when:
        1. An exception occurs (network error, timeout, etc.)
        2. An HTTP error occurs (status != 200)

        It signals the failure to the main process via shared state,
        then calls on_completion() to unblock dependent nodes.

        Args:
            response: The HTTP response (may be None for network errors)
            config: API configuration
            tokenizer: Tokenizer for token counting
            exception: The exception that occurred
            lora_adapter: Optional LoRA adapter name

        Returns:
            OTelInferenceInfo with empty output
        """
        logger.error(f"Request failed for node {self.node_id}: {type(exception).__name__}: {str(exception)}")

        # Extract session_id from node_id (format: "session_id:node_xxx")
        session_id = self.node_id.split(":")[0] if ":" in self.node_id else self.node_id

        # Mark the entire session as failed to prevent other nodes from processing
        self.shared_state.mark_session_failed(session_id)

        # Create empty inference info
        empty_info = OTelInferenceInfo(
            input_tokens=0,
            output_tokens=0,
            lora_adapter=lora_adapter,
            output_text="",  # Empty output for failed requests
        )

        # Call on_completion to register empty output and unblock dependents
        self.on_completion(empty_info)

        logger.info(f"Called on_completion() for failed node {self.node_id} to unblock dependent nodes")

        return empty_info


# ---------------------------------------------------------------------------
# OTelTraceReplayEvent — one event per graph node
# ---------------------------------------------------------------------------


@dataclass
class OTelTraceReplayEvent:
    """Represents a single LLM request event from an OTel trace, derived from a GraphCall."""

    call_id: str
    node_id: str
    file_index: int
    t_start_ms: int  # node start time (adjusted for time_scale + session offset)
    t_end_ms: int  # node end time
    model: str
    messages: List[Dict[str, Any]]  # original (recorded) messages — used as template
    expected_output: str
    input_segments: List[InputSegment]  # segment decomposition for output substitution
    expected_output_tokens: int
    temperature: Optional[float]
    max_tokens_recorded: Optional[int]
    # Predecessor node IDs (nodes that must complete before this one starts)
    predecessor_node_ids: List[str] = field(default_factory=list)
    wait_ms: int = 0


@dataclass
class OTelTraceSession:
    """Represents a complete session (one OTel file) as a ReplayGraph."""

    session_id: str
    file_path: Path
    file_index: int
    graph: ReplayGraph
    start_offset_ms: int = 0  # Offset for staggered session starts

def resolve_trace_files(trace_files):
    """
    Extract all relevant files from a list of paths.

    Handles two types of paths:
    1. Full path to a Otel file: /path/to/file.json
    2. Wildcard pattern: /path/to/*.json

    Args:
        trace_files: List of file paths or wildcard patterns

    Returns:
        List of resolved file paths (duplicates removed, sorted)

    Example:
        >>> paths = [
        ...     "/data/config.json",
        ...     "/logs/*.json",
        ...     "/output/**/*.json"  # recursive pattern
        ... ]
        >>> files = resolve_trace_files(paths)
    """
    all_files = set()  # Use set to avoid duplicates

    for path_pattern in trace_files:
        # Check if path contains wildcard characters
        if '*' in path_pattern or '?' in path_pattern:
            # Use glob to expand the pattern
            # recursive=True enables ** pattern for recursive matching
            matched_files = glob.glob(path_pattern, recursive=True)

            # Filter to only include files (not directories)
            for matched in matched_files:
                if Path(matched).is_file():
                    all_files.add(matched)
        else:
            # Direct path - check if file exists
            if Path(path_pattern).is_file():
                all_files.add(path_pattern)
            else:
                print(f"Warning: File not found: {path_pattern}")

    # Convert to sorted list for consistent output
    return [Path(f) for f in all_files]

class OTelTraceReplayDataGenerator(SessionGenerator, LazyLoadDataMixin):
    """
    Data generator that replays LLM requests from OpenTelemetry trace files.

    Features:
    - Processes multiple OTel JSON files from a directory
    - Each file becomes a separate session
    - Supports concurrent session replay
    - Maintains wall-clock timing with time_scale parameter
    - Enforces dependencies between requests
    - Supports model mapping or static model override
    - Output-aware: substitutes recorded assistant messages with actual LLM outputs
      for growing-context patterns (multi-turn, agent chains)
    """

    def __init__(
        self,
        api_config: APIConfig,
        config: DataConfig,
        tokenizer: Optional[CustomTokenizer],
        mp_manager: Optional[SyncManager] = None,
        base_seed: Optional[int] = None,
        num_workers: int = 1,
    ) -> None:
        super().__init__(api_config, config, tokenizer)

        if not hasattr(config, "otel_trace_replay") or config.otel_trace_replay is None:
            raise ValueError("otel_trace_replay configuration is required for OTelTraceReplayDataGenerator")

        self.otel_config = config.otel_trace_replay
        self.mp_manager = mp_manager
        self.num_workers = max(1, num_workers)
        self.base_seed = base_seed if base_seed is not None else 42

        # Determine loading mode: directory or list of files
        if self.otel_config.trace_directory:
            self.trace_dir: Optional[Path] = Path(self.otel_config.trace_directory)
            self.load_mode = "directory"

            if not self.trace_dir.exists():
                raise ValueError(f"Trace directory does not exist: {self.trace_dir}")

            if not self.trace_dir.is_dir():
                raise ValueError(f"Trace directory path is not a directory: {self.trace_dir}")
        elif self.otel_config.trace_files:
            # Multiple files mode
            self.trace_files_list = resolve_trace_files(self.otel_config.trace_files)
            self.load_mode = "files_list"
            self.trace_dir = None  # Not needed for files_list mode

            # Validate all files exist and are JSON
            for trace_file in self.trace_files_list:
                if not trace_file.exists():
                    raise ValueError(f"Trace file does not exist: {trace_file}")
                if not trace_file.is_file():
                    raise ValueError(f"Trace file path is not a file: {trace_file}")
                if trace_file.suffix != ".json":
                    raise ValueError(f"Trace file must be a JSON file: {trace_file}")
        else:
            raise ValueError("Either trace_directory or trace_files must be provided in otel_trace_replay config")

        # Cross-process state: node completions and session failures.
        # This is the only place Manager.dict() instances are created.
        self.shared_state = SessionSharedState(mp_manager)

        # Intra-worker output registry: plain dicts + asyncio.Event, no IPC.
        self.output_registry = NodeOutputRegistry()

        # Load and process all OTel trace files
        self.sessions: List[OTelTraceSession] = []
        self._load_trace_files()

        # Session state tracking (LoadGen controls which sessions are active)
        self.session_graph_state: Dict[str, SessionGraphState] = {}

        # Event index mappings
        self.event_to_session: Dict[int, str] = {}  # event_idx → session_id
        self.event_to_node: Dict[int, str] = {}  # event_idx → node_id

        if not self.sessions:
            raise ValueError("No valid OTel trace files found")

        # Build flat list of all events across all sessions for replay
        self._build_replay_schedule()

        logger.debug(f"Loaded {len(self.sessions)} sessions with {len(self.all_events)} total events")

    def _load_trace_files(self) -> None:
        """Load and process OTel JSON files based on the configured mode."""
        if self.load_mode == "files_list":
            # Multiple files mode: load specific list of files
            logger.info(f"Loading {len(self.trace_files_list)} specified trace files")
            for file_index, trace_file in enumerate(self.trace_files_list):
                try:
                    session = self._process_trace_file(trace_file, file_index)
                    if session:
                        self.sessions.append(session)
                        node_count = len(session.graph.nodes)
                        logger.info(f"Loaded session {session.session_id} from {trace_file.name} with {node_count} nodes")
                except Exception as e:
                    logger.error(f"Failed to process trace file {trace_file}: {e}")
                    if not self.otel_config.skip_invalid_files:
                        raise
        elif self.load_mode == "directory":
            # Directory mode: load all JSON files from the directory
            trace_files = sorted(self.trace_dir.glob("*.json"))

            if not trace_files:
                logger.warning(f"No JSON files found in {self.trace_dir}")
                return

            logger.info(f"Found {len(trace_files)} trace files in {self.trace_dir}")

            for file_index, trace_file in enumerate(trace_files):
                try:
                    session = self._process_trace_file(trace_file, file_index)
                    if session:
                        self.sessions.append(session)
                        node_count = len(session.graph.nodes)
                        logger.info(f"Loaded session {session.session_id} from {trace_file.name} with {node_count} nodes")
                except Exception as e:
                    logger.error(f"Failed to process trace file {trace_file}: {e}")
                    if not self.otel_config.skip_invalid_files:
                        raise

        # Randomize session order using base_seed for reproducibility
        random.seed(self.base_seed)
        random.shuffle(self.sessions)
        logger.info(f"Randomized session order using seed: {self.base_seed}")

        # Duplicate sessions if needed to meet total session requirements
        #self._duplicate_sessions_if_needed()

    def _duplicate_sessions_if_needed(self) -> None:
        """Duplicate sessions to ensure we have enough for high-concurrency testing.

        This is useful when the trace corpus is smaller than needed for stress testing.
        Sessions are duplicated with unique IDs to avoid conflicts.
        Target: 300 sessions (enough for most test scenarios)
        """
        target_sessions = 300
        current_count = len(self.sessions)

        if current_count >= target_sessions:
            logger.info(
                f"Session corpus sufficient: {current_count} sessions available "
                f"(target: {target_sessions})"
            )
            return

        # Calculate how many duplicates we need
        duplicates_needed = target_sessions - current_count
        logger.warning(
            f"Session corpus small: {current_count} sessions available. "
            f"Duplicating to reach {target_sessions} sessions for stress testing."
        )

        # Duplicate sessions in round-robin fashion
        original_sessions = list(self.sessions)
        duplicate_count = 0
        session_idx = 0

        while len(self.sessions) < target_sessions:
            # Get next session to duplicate (round-robin)
            source_session = original_sessions[session_idx % len(original_sessions)]
            session_idx += 1
            duplicate_count += 1

            # Create duplicate with unique ID
            duplicate_session = OTelTraceSession(
                session_id=f"{source_session.session_id}_dup{duplicate_count}",
                file_path=source_session.file_path,
                file_index=source_session.file_index + 10000 + duplicate_count,  # Unique file_index
                graph=source_session.graph,  # Graph can be shared (immutable)
                start_offset_ms=source_session.start_offset_ms,
            )

            self.sessions.append(duplicate_session)

        logger.info(
            f"Duplicated {duplicates_needed} sessions. "
            f"Total sessions now: {len(self.sessions)}"
        )

    def _process_trace_file(self, trace_file: Path, file_index: int) -> Optional[OTelTraceSession]:
        """Process a single OTel JSON trace file into a ReplayGraph session."""
        try:
            data = json.loads(trace_file.read_text(encoding="utf-8"))
        except json.JSONDecodeError as e:
            logger.error(f"Invalid JSON in {trace_file}: {e}")
            return None
        except Exception as e:
            logger.error(f"Error reading trace file {trace_file}: {e}")
            return None

        spans = data.get("spans") or []
        if not spans:
            logger.warning(f"No spans found in {trace_file}")
            return None

        try:
            raw_calls = build_raw_calls(spans, include_errors=self.otel_config.include_errors)
            if not raw_calls:
                logger.warning(f"No LLM calls found in {trace_file}")
                return None

            graph = build_graph(
                raw_calls,
                source_file=str(trace_file),
            )
        except Exception as e:
            logger.error(f"Error building graph from {trace_file}: {e}")
            return None

        # Use trace_id from first call as session_id, but make it unique by adding file_index
        # to handle cases where multiple files have the same trace_id
        base_session_id = raw_calls[0].trace_id or f"session_{file_index}"
        session_id = f"file{file_index}_{base_session_id}"

        return OTelTraceSession(
            session_id=session_id,
            file_path=trace_file,
            file_index=file_index,
            graph=graph,
        )

    def _build_replay_schedule(self) -> None:
        """Build the replay schedule using graph traversal (no time-based sorting).

        Creates event list and initializes session graph states for traversal.
        Sessions are activated on-demand based on concurrent_sessions limit.
        """
        self.all_events: List[OTelTraceReplayEvent] = []

        for session in self.sessions:
            # Initialize session graph state
            state = SessionGraphState(
                session_id=session.session_id,
                graph=session.graph,
                ready_nodes=set(),  # Will be populated when session is activated
                dispatched_nodes=set(),
                completed_nodes=set(),
                node_completion_times={},
                is_active=False,
                is_complete=False,
            )
            self.session_graph_state[session.session_id] = state

            # Build events for indexing (no time-based sorting)
            for node in session.graph.nodes.values():
                gc = node.call

                if not gc.messages:
                    logger.warning(f"Call {gc.call_id} in node {node.node_id} has no messages, skipping")
                    continue

                # Qualify node_id with session to avoid collisions
                qualified_node_id = f"{session.session_id}:{node.node_id}"
                qualified_predecessor_ids = [f"{session.session_id}:{pid}" for pid in node.predecessor_node_ids]

                # Rewrite source_node_id in input_segments
                qualified_segments = [
                    dc_replace(seg, source_node_id=f"{session.session_id}:{seg.source_node_id}")
                    if seg.source_node_id is not None
                    else seg
                    for seg in gc.input_segments
                ]

                event_idx = len(self.all_events)

                self.all_events.append(
                    OTelTraceReplayEvent(
                        call_id=gc.call_id,
                        node_id=qualified_node_id,
                        file_index=session.file_index,
                        t_start_ms=0,  # Not used in graph traversal
                        t_end_ms=0,  # Not used in graph traversal
                        model=gc.model,
                        messages=gc.messages,
                        expected_output=gc.expected_output,
                        input_segments=qualified_segments,
                        expected_output_tokens=gc.expected_output_tokens,
                        temperature=gc.temperature,
                        max_tokens_recorded=gc.max_tokens_recorded,
                        predecessor_node_ids=qualified_predecessor_ids,
                        wait_ms=node.wait_ms,
                    )
                )

                # Build index mappings
                self.event_to_session[event_idx] = session.session_id
                self.event_to_node[event_idx] = node.node_id

        # NO SORTING - events accessed by index via mappings

        logger.info(
            f"Built replay schedule: {len(self.all_events)} events across "
            f"{len(self.sessions)} sessions (graph-based traversal)"
        )

    def _get_effective_model(self, recorded_model: str) -> str:
        """Get the effective model name for a request."""
        if self.otel_config.use_static_model:
            # Use static model from config
            return self.otel_config.static_model_name
        else:
            # Use model mapping if provided
            if self.otel_config.model_mapping:
                return self.otel_config.model_mapping.get(recorded_model, recorded_model)
            return recorded_model


    def get_supported_apis(self) -> List[APIType]:
        """Return supported API types."""
        return [APIType.Chat]

    def is_prefered_worker_requested(self) -> bool:
        """Always True: all nodes of a session must run on the same worker for dependency waiting to work."""
        return True

    def get_session_count(self) -> int:
        """Return the total number of sessions (trace files) available for replay."""
        return len(self.sessions)

    def get_session_event_indices(self, session_index: int) -> List[int]:
        """Get the event indices for a specific session.

        Args:
            session_index: Index of the session (0-based)

        Returns:
            List of event indices (into self.all_events) that belong to this session

        Raises:
            IndexError: If session_index is out of range
        """
        if session_index < 0 or session_index >= len(self.sessions):
            raise IndexError(f"Session index {session_index} out of range (total: {len(self.sessions)})")

        session = self.sessions[session_index]
        # Find all events that belong to this session by matching file_index
        return [i for i, event in enumerate(self.all_events) if event.file_index == session.file_index]

    def get_session_info(self, session_index: int) -> Dict[str, Any]:
        """Get information about a specific session.

        Args:
            session_index: Index of the session (0-based)

        Returns:
            Dictionary with session metadata
        """
        if session_index < 0 or session_index >= len(self.sessions):
            raise IndexError(f"Session index {session_index} out of range (total: {len(self.sessions)})")

        session = self.sessions[session_index]
        event_indices = self.get_session_event_indices(session_index)

        return {
            "session_id": session.session_id,
            "file_path": str(session.file_path),
            "file_index": session.file_index,
            "num_events": len(event_indices),
            "num_nodes": len(session.graph.nodes),
            "start_offset_ms": session.start_offset_ms,
        }

    def get_session_events(self, session_index: int) -> List[LazyLoadInferenceAPIData]:
        """Get all events for a session, all assigned to the same worker.

        Assigning a deterministic worker to every event in a session ensures that
        all nodes run on the same event loop, which is required for dependency
        waiting to work correctly. The assignment is based on a hash of the session
        ID, so it is stable within a single run but not across runs.
        """
        session = self.sessions[session_index]
        event_indices = self.get_session_event_indices(session_index)
        session_worker_id = abs(hash(session.session_id)) % self.num_workers
        return [
            LazyLoadInferenceAPIData(data_index=idx, prefered_worker_id=session_worker_id)
            for idx in event_indices
        ]

    def build_session_metric(
        self,
        session_id: str,
        stage_id: int,
        start_time: float,
        end_time: float,
    ) -> SessionLifecycleMetric:
        """Build a SessionLifecycleMetric for a completed session.

        Token totals are left at 0 here and filled in later by the report
        generator once all metrics have been collected (the multiprocess
        collector only exposes metrics after the full run completes).

        Args:
            session_id: The session ID
            stage_id: The stage this session ran in
            start_time: Wall-clock epoch when the session was dispatched
            end_time: Wall-clock epoch when the session completed
        """
        state = self.session_graph_state.get(session_id)
        if state is None:
            raise ValueError(f"Unknown session: {session_id}")

        # Find the file_path for this session
        file_path = ""
        for session in self.sessions:
            if session.session_id == session_id:
                file_path = str(session.file_path)
                break

        num_nodes = len(state.graph.nodes)
        num_nodes_completed = len(state.completed_nodes)

        return SessionLifecycleMetric(
            session_id=session_id,
            stage_id=stage_id,
            file_path=file_path,
            start_time=start_time,
            end_time=end_time,
            duration_sec=end_time - start_time,
            num_nodes=num_nodes,
            num_nodes_completed=num_nodes_completed,
        )

    def activate_session(self, session_id: str) -> None:
        """Internal method to activate a session (mark nodes as ready).

        This is called by LoadGen when it decides to start a session.
        """
        state = self.session_graph_state.get(session_id)
        if state is None:
            logger.warning(f"Attempted to activate unknown session: {session_id}")
            return

        state.is_active = True

        # Find and activate root nodes (no predecessors)
        root_nodes = {node_id for node_id, node in state.graph.nodes.items() if not node.predecessor_node_ids}
        state.ready_nodes.update(root_nodes)

        logger.info(f"Activated session {session_id} with {len(root_nodes)} root nodes")

    def check_session_completed(self, session_id: str) -> bool:
        """Check if a specific session has completed all its nodes.

        Args:
            session_id: The session ID to check

        Returns:
            True if all nodes in the session have completed, False otherwise
        """
        state = self.session_graph_state.get(session_id)
        if state is None:
            logger.warning(f"Attempted to check unknown session: {session_id}")
            return False

        # Check completion tracker for all nodes in this session
        for node_id in state.graph.nodes.keys():
            qualified_node_id = f"{session_id}:{node_id}"
            if self.shared_state.is_node_completed(qualified_node_id):
                # Record in local state if not already recorded
                if node_id not in state.completed_nodes:
                    completion_time = self.shared_state.get_node_completion_time(qualified_node_id)
                    state.completed_nodes.add(node_id)
                    state.node_completion_times[node_id] = completion_time

        # Session is complete if all nodes are complete
        is_complete = len(state.completed_nodes) == len(state.graph.nodes)

        if is_complete and not state.is_complete:
            state.is_complete = True
            logger.info(f"Session {session_id} completed all {len(state.graph.nodes)} nodes")

        return is_complete

    def load_lazy_data(self, data: LazyLoadInferenceAPIData) -> InferenceAPIData:
        """Load the actual request data for a given index.

        Returns an OTelChatCompletionAPIData instance carrying the dependency
        information (predecessor_node_ids, wait_ms, input_segments). The worker
        calls wait_for_predecessors_and_substitute() on this object before
        dispatching the HTTP request, which suspends the coroutine until all
        predecessors have completed and then substitutes their outputs into the
        message list.
        """
        n = data.data_index

        if n >= len(self.all_events):
            raise IndexError(f"Event index {n} out of range (total: {len(self.all_events)})")

        event = self.all_events[n]

        # Convert messages to ChatMessage objects (substitution happens later in the worker).
        chat_messages = []
        for msg in event.messages:
            role = msg.get("role", "user")
            content = msg.get("content", "")

            # Handle content that might be a list (tool blocks)
            if isinstance(content, list):
                content_parts = []
                for block in content:
                    if isinstance(block, dict):
                        if block.get("type") == "text":
                            content_parts.append(block.get("text", ""))
                        else:
                            content_parts.append(json.dumps(block))
                    else:
                        content_parts.append(str(block))
                content = " ".join(content_parts)

            chat_messages.append(ChatMessage(role=role, content=str(content)))

        # Use expected_output_tokens (from trace) so downstream prefix matching works.
        # Fall back to config default if not available.
        max_tokens = event.expected_output_tokens or self.otel_config.default_max_tokens

        # Return OTelChatCompletionAPIData with dependency info.
        # The worker calls wait_for_predecessors_and_substitute() before dispatching.
        return OTelChatCompletionAPIData(
            messages=chat_messages,
            max_tokens=max_tokens,
            node_id=event.node_id,
            registry=self.output_registry,
            shared_state=self.shared_state,
            # Pass dependency info for the worker to use during async waiting
            predecessor_node_ids=event.predecessor_node_ids,
            wait_ms=event.wait_ms,
            input_segments=event.input_segments,
            original_messages=event.messages,
            expected_output_content=event.expected_output,
        )

    def _find_event_index(self, session_id: str, node_id: str) -> int:
        """Find the event index for a given session and node_id.

        Uses the event_to_session and event_to_node mappings for O(n) lookup.
        Could be optimized with a reverse index if needed.
        """
        qualified_node_id = f"{session_id}:{node_id}"

        for idx, event in enumerate(self.all_events):
            if event.node_id == qualified_node_id:
                return idx

        raise ValueError(
            f"Event not found: session={session_id}, node={node_id}. This indicates a bug in the graph traversal logic."
        )

    # Made with Bob

    def cleanup_session(self, session_id: str) -> None:
        """Clean up memory for a completed session.

        Removes all node outputs, messages, and completion tracking data
        for the specified session to prevent memory leaks in long-running
        benchmarks with many sessions.

        Args:
            session_id: The session ID to clean up
        """
        state = self.session_graph_state.get(session_id)
        if state is None:
            logger.warning(f"Attempted to cleanup unknown session: {session_id}")
            return

        # Count nodes for logging
        node_count = len(state.graph.nodes)

        # Remove node outputs and messages from registry
        for node_id in state.graph.nodes.keys():
            qualified_node_id = f"{session_id}:{node_id}"


            # Remove from output registry
            self.output_registry._node_output_text.pop(qualified_node_id, None)
            self.output_registry._node_input_messages.pop(qualified_node_id, None)
            self.output_registry._node_events.pop(qualified_node_id, None)

            # Remove from shared completion tracker.
            # We retain completion times for report generation; uncomment to reclaim memory.
            # self.shared_state._node_completions.pop(qualified_node_id, None)

        # Remove session state
        del self.session_graph_state[session_id]

        logger.debug(f"Cleaned up session {session_id}: removed {node_count} nodes from memory")
