# Copyright 2026 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Public surface for the BR0.2.1 pydantic models, which come from the
# llmd-benchmark-report package. Import from this module rather than the
# package directly so a schema bump only touches this file.
from llmd_benchmark_report.base import (
    UNITS_BANDWIDTH,
    UNITS_GEN_LATENCY,
    UNITS_GEN_THROUGHPUT,
    UNITS_MEDIA_THROUGHPUT,
    UNITS_MEMORY,
    UNITS_PORTION,
    UNITS_POWER,
    UNITS_QUANTITY,
    UNITS_RATIO,
    UNITS_REQUEST_THROUGHPUT,
    UNITS_TIME,
    BenchmarkReport,
    Units,
    WorkloadGenerator,
)
from llmd_benchmark_report.schema_v0_2 import (
    VERSION,
    AggregateLatency,
    AggregateRequestPerformance,
    AggregateRequests,
    AggregateThroughput,
    AudioPayloadStats,
    BenchmarkReportV021,
    Component,
    ComponentHealth,
    ComponentMetadata,
    ComponentNative,
    ComponentObservability,
    ControllerReplicaStatus,
    Distribution,
    ImagePayloadStats,
    Load,
    LoadMetadata,
    LoadNative,
    LoadPrefix,
    LoadSource,
    LoadStandardized,
    MediaPayloadStats,
    MultiModalRequests,
    MultiTurn,
    Observability,
    PodStartupInfo,
    PodStartupTimes,
    ReplicaHealth,
    ReplicaStatus,
    ReplicaStatusSnapshot,
    RequestPerformance,
    ResourceMetrics,
    Results,
    Run,
    RunTime,
    Scenario,
    SequenceLength,
    Statistics,
    TimeSeriesData,
    TimeSeriesLatency,
    TimeSeriesPoint,
    TimeSeriesRequestPerformance,
    TimeSeriesResourceMetrics,
    TimeSeriesThroughput,
    VideoPayloadStats,
    VisualPayloadStats,
)
from llmd_benchmark_report.schema_v0_2_components import COMPONENTS

__all__ = [
    "AggregateLatency",
    "AggregateRequestPerformance",
    "AggregateRequests",
    "AggregateThroughput",
    "AudioPayloadStats",
    "BenchmarkReport",
    "BenchmarkReportV021",
    "COMPONENTS",
    "Component",
    "ComponentHealth",
    "ComponentMetadata",
    "ComponentNative",
    "ComponentObservability",
    "ControllerReplicaStatus",
    "Distribution",
    "ImagePayloadStats",
    "Load",
    "LoadMetadata",
    "LoadNative",
    "LoadPrefix",
    "LoadSource",
    "LoadStandardized",
    "MediaPayloadStats",
    "MultiModalRequests",
    "MultiTurn",
    "Observability",
    "PodStartupInfo",
    "PodStartupTimes",
    "ReplicaHealth",
    "ReplicaStatus",
    "ReplicaStatusSnapshot",
    "RequestPerformance",
    "ResourceMetrics",
    "Results",
    "Run",
    "RunTime",
    "Scenario",
    "SequenceLength",
    "Statistics",
    "TimeSeriesData",
    "TimeSeriesLatency",
    "TimeSeriesPoint",
    "TimeSeriesRequestPerformance",
    "TimeSeriesResourceMetrics",
    "TimeSeriesThroughput",
    "UNITS_BANDWIDTH",
    "UNITS_GEN_LATENCY",
    "UNITS_GEN_THROUGHPUT",
    "UNITS_MEDIA_THROUGHPUT",
    "UNITS_MEMORY",
    "UNITS_PORTION",
    "UNITS_POWER",
    "UNITS_QUANTITY",
    "UNITS_RATIO",
    "UNITS_REQUEST_THROUGHPUT",
    "UNITS_TIME",
    "Units",
    "VERSION",
    "VideoPayloadStats",
    "VisualPayloadStats",
    "WorkloadGenerator",
]
