# inference-perf/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "inference-perf.fullname" . }}-config
  labels:
    {{- include "inference-perf.labels" . | nindent 4 }}
data:
  config.yml: |
    {{- $config := .Values.config | deepCopy -}}
    {{- if eq $config.server.base_url "http://0.0.0.0:8000" -}}
      {{- $_ := set $config.server "base_url" (printf "http://%s-sim:8000" (include "inference-perf.fullname" .)) -}}
    {{- end -}}
    {{- toYaml $config | nindent 4 }}