# inference-perf/templates/job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "inference-perf.fullname" . }}-job
  labels:
    {{- include "inference-perf.labels" . | nindent 4 }}
    app: inference-perf
spec:
  template:
    metadata:
      labels:
        {{- include "inference-perf.selectorLabels" . | nindent 8 }}
        app: inference-perf
    spec:
      restartPolicy: Never
      containers:
        - name: inference-perf-container
          image: {{ .Values.job.image }}
          command: ["inference-perf"]
          args: 
            - "--config_file"
            - "{{ .Values.configMap.mountPath }}/{{ .Values.configMap.fileName }}"
            - "--log-level"
            - {{ .Values.logLevel }}
          env:
{{- if .Values.hfToken }}
          - name: HF_TOKEN
            valueFrom:
              secretKeyRef:
                name: {{ include "inference-perf.hfSecret" . }}
                key: {{ include "inference-perf.hfKey" . }}
{{- end }}
          volumeMounts:
            - name: config-volume
              mountPath: {{ .Values.configMap.mountPath }}
              readOnly: true
          resources:
            requests:
              memory: {{ .Values.job.memory }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "inference-perf.fullname" . }}-config