{{- if .Values.redis.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "inference-perf.fullname" . }}-redis
  labels:
    {{- include "inference-perf.labels" . | nindent 4 }}
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "inference-perf.selectorLabels" . | nindent 6 }}
      app: redis
  template:
    metadata:
      labels:
        {{- include "inference-perf.selectorLabels" . | nindent 8 }}
        app: redis
    spec:
      containers:
      - name: redis
        image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "inference-perf.fullname" . }}-redis
  labels:
    {{- include "inference-perf.labels" . | nindent 4 }}
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    {{- include "inference-perf.selectorLabels" . | nindent 4 }}
    app: redis
{{- end }}
