# inference-perf/templates/secret.yaml
{{- if .Values.hfToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "inference-perf.hfSecret" . }}
  labels:
    {{- include "inference-perf.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ include "inference-perf.hfKey" . }}: {{ .Values.hfToken | quote }}
{{- end }}
