load:
  type: constant
  stages:
  - rate: 1
    duration: 30
api: completion
server:
  type: vllm
  model_name: HuggingFaceTB/SmolLM2-135M-Instruct
  base_url: http://0.0.0.0:8000
tokenizer:
  pretrained_model_name_or_path: HuggingFaceTB/SmolLM2-135M-Instruct
data:
  type: synthetic
  input_distribution:
    min: 10
    max: 100
    mean: 50
    std: 10
    total_count: 100
