api:
  type: chat
  streaming: true
server:
  type: vllm
  model_name: Qwen/Qwen3-VL-8B-Instruct
  base_url: http://qwen3-32b-vllm-service.test-ns.svc.cluster.local:8000
data:
  type: synthetic
  input_distribution: { type: fixed, min: 32, max: 32, mean: 32 }
  output_distribution: { type: fixed, min: 16, max: 16, mean: 16 }
  multimodal:
    image:
      count: { type: fixed, min: 1, max: 1, mean: 1 }
      insertion_point: 0.0
      resolutions:
        - resolution: "1080p"
          weight: 1.0
    video:
      count: { type: fixed, min: 1, max: 1, mean: 1 }
      insertion_point: 1.0
      profiles:
        - profile: { resolution: "720p", frames: 32 }
          weight: 1.0
load:
  type: constant
  stages:
    - rate: 1
      duration: 10
  num_workers: 1
report:
  request_lifecycle:
    summary: true
    per_stage: true
