name: Python Linting and Type Checks

on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:

jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up Python PDM
        uses: pdm-project/setup-pdm@v4
      - name: Do Linting and Type Checks
        run: |
          make validate
