name: Python Linting and Type Checks

on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:

jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Set up PDM
        uses: pdm-project/setup-pdm@v4
      - name: Install dependencies
        run: |
          pdm sync -d
      - name: Do Linting and Type Checks
        run: |
          pdm run validate
