name: Unit Tests

on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:

jobs:
  format-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.13']
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Configure PDM to use local venv
        run: pdm config venv.in_project true
      - name: Install dependencies
        run: |
          pdm sync -d
          pdm install -G dev
          pdm install -G analysis
      - name: Add .venv/bin to PATH
        run: echo "$PWD/.venv/bin" >> $GITHUB_PATH
      - name: Setup Buf
        uses: bufbuild/buf-setup-action@v1
      - name: Generate Protobuf
        run: buf generate
      - name: Run Unit Tests
        run: |
          PYTHONPATH=api/generated/python pdm run test
